---
- name: Mariadb server is running
  hosts: database_dev
  vars:
    mariadb_packages:
      - mariadb-server
      - python3-PyMySQL
  tasks:
    - name: Mariadb packages are installed
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ mariabd_packages }}"
    - name: start MariaDB service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true
