---
- name: Loop Register Test
  gather_facts: no
  hosts: localhost
  vars:
    mail_services:
      - postfix
      - dovecot
  tasks:
    - name: Postfix and Dovecot are running
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
      loop: "{{ mail_services }}"