---
- name: Httpd conf file update
  hosts: localhost
  tasks:
    - name: copy demo.example.conf configuration template
      ansible.builtin.template:
        src: /var/lib/templates/demo.example.conf.template
        dest: /etc/httpd/conf.d/demo.example.conf
      notify:
        - restart mysql
        - restart apache
  handlers:
    - name: restart mysql
      ansible.builtin.service:
        name: mariadb
        state: restarted
    - name: restart apache
      ansible.builtin.service:
        name: httpd
        state: restarted