---
- name: Test Variable is Defined Demo
  hosts: localhost
  vars:
    my_service: httpd
  tasks:
    - name: "{{ my_service }} package is installed"
      ansible.builtin.dnf:
        name: "{{ my_service }}"
        state: present 
      when: my_service is defined